# Generated by Django 5.1.5 on 2025-03-08 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitems',
            old_name='quatity',
            new_name='quantity',
        ),
    ]
